//todos
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_RODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const SELECT_TODO = 'SELECT_TODO';

// recording
export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const START_SESSION_REPLAY = 'START_SESSION_REPLAY';
export const END_SESSION_REPLAY = 'END_SESSION_REPLAY';
export const RESET_APP_STATE = 'RESET_APP_STATE';
export const DELETE_RECORDED_SESSION = 'DELETE_RECORDED_SESSION';
